### ISSUE TITLE
Some icons are not in the right place when using right-to-left writing

### ISSUE THREAD

**Issue by Lotopi** [enteraname74/MusicPlayer#2]
### Bug description

When using right-to-left writing (RTL), the forward and backward icons are in the wrong place.

### Steps to reproduce

- Switch to RTL writing in "Developer options" in the phone settings.
- Open the application and play a song.

### Screenshots

[Screenshot](https://user-images.githubusercontent.com/40468597/188938241-5d97e534-9c77-4c8a-83dc-e8ac1dcf538a.jpg)

### Device info

Android version: 12
Music Player version: 1.1.8

**Comment by enteraname74** [comment]
Thanks for all the details, it helped me a lot in order to correct this issue.
The problem is now normally fixed and the result will appear in the next release.
